# Generated by Django 3.1.5 on 2021-01-11 08:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_first_name', models.CharField(max_length=100)),
                ('customer_last_name', models.CharField(max_length=100)),
                ('national_code', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(help_text='11 Character', max_length=11, verbose_name='PhoneNumber')),
                ('customer_address', models.TextField(help_text='Please Enter Complete Your Address Here', max_length=1000)),
                ('customer_city', models.CharField(blank=True, choices=[('1', 'اراک'), ('2', 'اردبیل'), ('3', 'ارومیه'), ('4', 'اصفهان'), ('5', 'اهواز'), ('6', 'ایلام'), ('7', 'بجنورد'), ('8', 'بندرعباس'), ('9', 'بوشهر'), ('10', 'بیرجند'), ('11', 'تبریز'), ('12', 'تهران'), ('13', 'خرم\u200cآباد'), ('14', 'رشت'), ('15', 'زاهدان'), ('16', 'زنجان'), ('17', 'ساری'), ('18', 'سمنان'), ('19', 'سنندج'), ('20', 'شهرکرد'), ('21', 'شیراز'), ('22', 'قزوین'), ('23', 'قم'), ('24', 'کرج'), ('25', 'کرمان'), ('26', 'کرمانشاه'), ('27', 'گرگان'), ('28', 'مشهد'), ('29', 'همدان'), ('30', 'یاسوج'), ('31', 'یزد')], default='12', help_text='Please Choose your city', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('store_phone', models.CharField(help_text='11 Character', max_length=11, verbose_name='PhoneNumber')),
                ('store_address', models.TextField(help_text='Please Enter Complete Your Address Here', max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('store_city', models.CharField(blank=True, choices=[('1', 'اراک'), ('2', 'اردبیل'), ('3', 'ارومیه'), ('4', 'اصفهان'), ('5', 'اهواز'), ('6', 'ایلام'), ('7', 'بجنورد'), ('8', 'بندرعباس'), ('9', 'بوشهر'), ('10', 'بیرجند'), ('11', 'تبریز'), ('12', 'تهران'), ('13', 'خرم\u200cآباد'), ('14', 'رشت'), ('15', 'زاهدان'), ('16', 'زنجان'), ('17', 'ساری'), ('18', 'سمنان'), ('19', 'سنندج'), ('20', 'شهرکرد'), ('21', 'شیراز'), ('22', 'قزوین'), ('23', 'قم'), ('24', 'کرج'), ('25', 'کرمان'), ('26', 'کرمانشاه'), ('27', 'گرگان'), ('28', 'مشهد'), ('29', 'همدان'), ('30', 'یاسوج'), ('31', 'یزد')], default='12', help_text='Please Choose your city', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, choices=[('1', 'Lundry Service'), ('2', 'Dry Cleaning & Ironed Laundry'), ('3', 'Home & Bedding')], default='1', max_length=1)),
                ('product_price', models.CharField(max_length=100)),
                ('product_customer', models.ManyToManyField(blank=True, help_text='Please Select customer for this Product', to='mysite.Customers')),
                ('product_stores', models.ManyToManyField(blank=True, help_text='Please Select Stores for this Product', to='mysite.Stores')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular orders', primary_key=True, serialize=False)),
                ('order_name', models.CharField(help_text='Please Enter your order name or comment', max_length=400)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('order_status', models.CharField(blank=True, choices=[('w', 'Waiting to accept by nearest store'), ('a', 'accept by store'), ('n', 'not accept'), ('p', 'In Progress'), ('r', 'Ready'), ('d', 'Delivered')], default='w', max_length=1)),
                ('delivered_date', models.DateField(blank=True, null=True)),
                ('order_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.customers')),
                ('order_store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.stores')),
                ('product_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.products')),
            ],
        ),
    ]
