# Generated by Django 3.1.5 on 2021-01-11 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20210111_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysite.store'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, choices=[('LaundryService', 'Laundry Service'), ('Dry Cleaning', 'Dry Cleaning & Ironed Laundry'), ('Home & Bedding', 'Home & Bedding')], default='LaundryService', max_length=40),
        ),
    ]
